### ISSUE TITLE
Way to customize swagger route path

### ISSUE THREAD

**Issue by webdevog** [InfyOmLabs/swagger-generator#3]
Hello.
Is there a way to customize templates using MODEL_NAME_PLURAL_SNAKE instead of MODEL_NAME_PLURAL_CAMEL? (like I did in https://github.com/webdevog/swagger-generator)
I can't find a way to configure it.
My issue is that infyomlabs/laravel-generator generates by default routes  in snake_case style and infyomlabs/swagger-generator makes swagger annotations using camelCase and as result I have wrond routes in documentation until I start using  my fork https://github.com/InfyOmLabs/swagger-generator/compare/master...webdevog:master
Any suggestions? 
Thank you

**Comment by webdevog** [comment]
Any ideas, guys?

**Comment by fuguelike** [comment]
I have this same issue - the generated doc names are not the same as the laravel-generator routes.

**Comment by WilChrist** [comment]
I think once you're app is ready for production, you can set `auto-generate` to **false** in the swaggverl.php config file, then modify manually your route path in api-docs.json

**Comment by MACscr** [comment]
Did they really never resolve this? Frustrating to see github issues ignored by devs.

**Comment by mitulgolakiya** [comment]
Changed route generation to dashed version. so routes for multi keywords will be generated like `ChatMessage` model's routes will be `chat-messages`.

Also added fix to laravel-generator. Use the latest version of both swagger-generator and laravel-generator to resolve the issue.
