### ISSUE TITLE
add support for OpenAPI spec v3 annotation

### ISSUE THREAD

**Issue by alphaolomi** [InfyOmLabs/swagger-generator#5]
Hello, great work with the Swagger generator 

So the [appointer/swaggervel](https://github.com/appointer/swaggervel) is archived by the owner. It is now read-only.

I opted to use https://github.com/DarkaOnLine/L5-Swagger as the generator ,

Now "darkaonline/l5-swagger" latest version that is 8 is compatible with OpenAPI Spec  version 3 only,

This package has only "@SWG (SWAGGER annotations) support." stubs it would be nice to have OpenAPI spec v3 annotation (@OA)

**Comment by alphaolomi** [comment]
Hello  @mitulgolakiya 👀

**Comment by mitulgolakiya** [comment]
Hi, we are already working on this and almost done. We will be pushing Open API Specification support by next week probably.

**Comment by alphaolomi** [comment]
Thanks in advance, really looking forward to it.
