### ISSUE TITLE
appointer/swaggervel This package is abandoned and no longer maintained. No replacement package was suggested.

### ISSUE THREAD

**Issue by rupeszh** [InfyOmLabs/swagger-generator#7]
**appointer/swaggervel   package is no more maintained or abondoned.

**Comment by mitulgolakiya** [comment]
Just added support for https://github.com/DarkaOnLine/L5-Swagger. Soon docs will be updated on https://infyom.com/open-source/laravelgenerator/docs/generator-options#swagger
